## Pre-commit setup

ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
  autoupdate_commit_msg: |
    ci(pre-commit): autoupdate hook versions

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Running black in all files.

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: Check if python files are valid syntax for the ast parser
      - id: check-case-conflict
        name: Check for case conflict on file names for case insensitive systems.
      - id: check-merge-conflict
        name: Check for merge conflict syntax.
      - id: check-toml
        name: Check TOML files for valid syntax.
      - id: check-yaml
        name: Check YAML files for valid syntax.
      - id: debug-statements
        name: Check for debug statements.
      - id: end-of-file-fixer
        name: Check for only one newline character at EOL.
      - id: trailing-whitespace
        name: Check for trailing whitespace.
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        # Non-zero means user can check changes before committing.
        args: [--fix, --exit-non-zero-on-fix]
        name: Linting all files with ruff.
